import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { nanoid } from "nanoid";
import axios from "axios";

const OAuth: NextPage = (props: any) => {
  const [data, setData] = useState();
  const router = useRouter();
  console.log(props);

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{props.access_token}</main>
    </div>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const code = context.query["code"];
  console.log(code);

  const buf = Buffer.from(process.env.CLIENT_ID + ":" + process.env.CLIENT_SECRET);
  const auth = buf.toString("base64");

  const url = `https://auth.myminifactory.com/v1/oauth/tokens`;
  const params = new URLSearchParams();
  params.append("grant_type", "authorization_code");
  params.append("code", code as string);
  params.append("redirect_uri", "http://localhost:3000/oauth");
  const res = await axios.post(url, params, {
    headers: {
      Authorization: "Basic " + auth,
    },
  });
  // Pass data to the page via props
  return { props: res.data };
}

export default OAuth;

// http://localhost:8080/oauth?code=S0UkswRKdFtPP2jD3HeLsAdD-eNuprHga6UKbkLJGqMjf7irk0UtkL07GbE0KVhN&state=QQnwa5g3nqt0z1gkLPQgS
